spring.application.name=mail-buddy

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saranmuruga437@gmail.com
spring.mail.password=uqik ibga lfbb zosk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Logs
logging.file.name=logs/application.log   
logging.file.path=logs                  
logging.level.root=INFO     

#swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
            

