spring.application.name=mail-buddy

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saranmuruga437@gmail.com
spring.mail.password=uqik ibga lfbb zosk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Logs
logging.file.name=logs/application.log   
logging.file.path=logs                  
logging.level.root=INFO     

#swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#Actuators Logs
management.endpoints.web.exposure.include=loggers
management.endpoints.web.base-path=/actuator
management.endpoint.loggers.enabled=true
spring.security.user.name=admin
spring.security.user.password=admin

management.endpoint.health.enabled=true
management.endpoints.web.exposure.include=health,info


spring.application.name=my-spring-boot-app
spring.boot.admin.client.url=http://localhost:8080

management.endpoint.logfile.enabled=true
management.endpoints.web.exposure.include=logfile

management.endpoint.logfile.external-file=log-file/application.log

spring.boot.admin.client.metadata.logfile=/actuator/logfile





            

